// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyymqvwkzdsvyrbhwwzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5eW1xdndremRzdnlyYmh3d3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MjgxMDcsImV4cCI6MjA2MDAwNDEwN30.UaK-YgEZIxKI-XK_SlNXwGJcOYgcPy0P_HJc7N02p8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);